#!/bin/bash

do_test () {
	export IODEPTH=$2
	export IOTYPE=$1
	res=`fio auto.ini --minimal`
	echo -en "$IOTYPE\t$IODEPTH\t"
	case $IOTYPE in
		randread)
			echo $res|awk -F ';' '{print $7"\t"$8"\t"$40}'
			;;
		randwrite)
			echo $res|awk -F ';' '{print $48"\t"$49"\t"$81}'
			;;
		*)
			echo bad call
	esac
		
}

if test -x `which fio`;
then
	#write tests
	for iodepth in `seq 1 32` 48 64 96 128 192 256;
	do
		do_test randwrite $iodepth $1.write
	done

	#read tests
	for iodepth in `seq 1 32` 48 64 96 128 192 256;
	do
		do_test randread $iodepth $2.read
	done
else
	echo fio not found, please install fio and edit the auto.ini
fi
