#!/bin/bash

do_test () {
	export IODEPTH=$2
	export IOTYPE=$1
	res=`fio auto.ini --minimal`
	echo -en "$IODEPTH;"
	case $IOTYPE in
		randread)
			echo $res|awk -F ';' '{print $7";"$8";"$40}'
			;;
		randwrite)
			echo $res|awk -F ';' '{print $48";"$49";"$81}'
			;;
		*)
			echo bad call
	esac
		
}

if test -x `which fio`;
then
	#write tests
	echo "iodepth;bandwidth;IOPS;latency"
	for iodepth in `seq 1 36`;
	do
		do_test randwrite $iodepth $1.write
	done

	#read tests
	echo "iodepth;bandwidth;IOPS;latency"
	for iodepth in `seq 1 36`;
	do
		do_test randread $iodepth $2.read
	done
else
	echo fio not found, please install fio and edit the auto.ini
fi
